name: YapYap
options:
  bundleIdPrefix: dev.yapyap
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    # Team ID from Apple Developer account (sandeeptnvs@gmail.com)
    DEVELOPMENT_TEAM: "C4HCL432GF"
  configs:
    Debug:
      # Ad-hoc signing for local development builds — fast, no certificate needed
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGN_STYLE: Manual
    Release:
      # Automatic signing with Developer ID Application for distribution
      # Requires "Developer ID Application" certificate in Keychain
      # Create at: https://developer.apple.com/account/resources/certificates/add
      CODE_SIGN_IDENTITY: "Developer ID Application"
      CODE_SIGN_STYLE: Manual

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    from: "0.7.9"
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift.git
    from: "0.30.0"
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    from: "2.29.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts.git
    from: "2.0.0"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern.git
    from: "1.0.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle.git
    from: "2.0.0"
  SelectedTextKit:
    url: https://github.com/tisfeng/SelectedTextKit.git
    from: "2.6.0"
  swift-argument-parser:
    url: https://github.com/apple/swift-argument-parser.git
    from: "1.3.0"

targets:
  YapYap:
    type: application
    platform: macOS
    sources:
      - path: YapYap
    resources:
      - path: YapYap/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.yapyap.app
        INFOPLIST_FILE: YapYap/Info.plist
        CODE_SIGN_ENTITLEMENTS: YapYap/YapYap.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: true
      configs:
        Release:
          ENABLE_HARDENED_RUNTIME: true
          OTHER_CODE_SIGN_FLAGS: "--timestamp"
    dependencies:
      - package: WhisperKit
      - package: FluidAudio
      - package: mlx-swift
        product: MLX
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon
      - package: KeyboardShortcuts
      - package: LaunchAtLogin
      - package: Sparkle
      - package: SelectedTextKit
    entitlements:
      path: YapYap/YapYap.entitlements
      properties:
        # Microphone access for speech-to-text
        com.apple.security.device.audio-input: true
        # Accessibility API: read selected text, synthetic key events for paste
        com.apple.security.automation.apple-events: true
        # Disable sandbox: required for CGEvent (synthetic keystrokes) and AXUIElement
        com.apple.security.app-sandbox: false

  YapYapTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: YapYapTests
    dependencies:
      - target: YapYap
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.yapyap.app.tests
        GENERATE_INFOPLIST_FILE: YES

  YapYapBench:
    type: tool
    platform: macOS
    sources:
      - path: YapYapBench
      - path: YapYap/Core/LLM
        excludes:
          - "MLXEngine.swift"
      - path: YapYap/Core/STT
      - path: YapYap/Core/Context
      - path: YapYap/Core/Models/ModelStorage.swift
      - path: YapYap/Utilities/YapYapError.swift
      - path: YapYap/Utilities/PersonalDictionary.swift
      - path: YapYap/Utilities/CorrectionDiffer.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.yapyap.bench
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - package: WhisperKit
      - package: FluidAudio
      - package: mlx-swift
        product: MLX
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon
      - package: swift-argument-parser
        product: ArgumentParser
