// PasteManager.swift
// YapYap — Paste text into active app via clipboard + synthetic Cmd+V
//
// App Store sandbox compatible: uses CGEvent.post() which requires the PostEvent
// TCC privilege (shown as "Accessibility" in System Settings). This is separate from
// full Accessibility API access and works within App Sandbox.
// See: https://developer.apple.com/forums/thread/789896
import AppKit
import Carbon.HIToolbox

class PasteManager {

    /// Pasteboard markers per nspasteboard.org convention — tells clipboard managers
    /// (Maccy, Paste.app, etc.) not to record this temporary write.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Skip saving/restoring clipboard if it exceeds this size (avoids OOM with large images).
    private static let maxPasteboardSaveBytes = 10 * 1024 * 1024 // 10 MB

    /// Paste text into the target app via clipboard + synthetic Cmd+V.
    ///
    /// - Parameters:
    ///   - text: The text to paste.
    ///   - targetApp: The app to paste into (captured at recording start). Falls back to frontmost app.
    ///   - keepOnClipboard: When true (copyToClipboard setting), the clipboard keeps the
    ///     transcription after paste instead of being restored. Also omits the transient marker
    ///     so clipboard managers record the text.
    func paste(_ text: String, targetApp: NSRunningApplication? = nil, keepOnClipboard: Bool = false) {
        let resolvedApp = targetApp ?? NSWorkspace.shared.frontmostApplication
        let appName = resolvedApp?.localizedName ?? "unknown"
        NSLog("[PasteManager] Paste requested: \(text.count) chars → \(appName) (pid: \(resolvedApp?.processIdentifier ?? -1))")

        guard hasPostEventAccess() else {
            NSLog("[PasteManager] ❌ PostEvent permission not granted — paste skipped. Requesting permission.")
            requestPostEventAccess()
            // Still put text on clipboard so user can manually Cmd+V
            let pasteboard = NSPasteboard.general
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            NSLog("[PasteManager] Text placed on clipboard — user can paste manually with Cmd+V")
            return
        }

        pasteViaClipboard(text, targetApp: resolvedApp, keepOnClipboard: keepOnClipboard)
    }

    // MARK: - Permission Check

    /// Check if we have permission to post CGEvents (synthetic keystrokes).
    /// Uses the sandbox-compatible CGPreflightPostEventAccess API.
    private func hasPostEventAccess() -> Bool {
        return CGPreflightPostEventAccess()
    }

    /// Request permission to post CGEvents. Shows the system TCC dialog.
    private func requestPostEventAccess() {
        CGRequestPostEventAccess()
    }

    // MARK: - Clipboard + Cmd+V

    /// Save clipboard, set text, synthetic Cmd+V, optionally restore clipboard.
    private func pasteViaClipboard(_ text: String, targetApp: NSRunningApplication?, keepOnClipboard: Bool) {
        let pasteboard = NSPasteboard.general

        // Save ALL pasteboard items (not just .string) so we can restore rich content
        // (images, RTF, files) the user had copied. Skip if keepOnClipboard — no restore needed.
        let savedItems: [[(NSPasteboard.PasteboardType, Data)]]? = keepOnClipboard ? nil : savePasteboard(pasteboard)

        // Set new content
        pasteboard.clearContents()

        // Mark as transient so clipboard managers (Maccy, Paste.app) don't record
        // this temporary write — unless the user wants it kept on clipboard
        if !keepOnClipboard {
            let item = NSPasteboardItem()
            item.setString(text, forType: .string)
            item.setData(Data(), forType: Self.transientType)
            item.setData(Data(), forType: Self.autoGeneratedType)
            pasteboard.writeObjects([item])
        } else {
            pasteboard.setString(text, forType: .string)
        }
        NSLog("[PasteManager] Clipboard set: text length: \(text.count), keepOnClipboard: \(keepOnClipboard)")

        // Ensure the target app is ready to receive the paste.
        // Allow 50ms for clipboard write to propagate before activating the app.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            self.activateTargetApp(targetApp)

            // Allow 100ms after activation for the app to become ready to receive input.
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.10) {
                self.simulatePaste()

                // Retry: send a second Cmd+V after a short delay if the first one was
                // silently dropped (common when target app isn't fully activated yet).
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.20) {
                    if let app = targetApp, !app.isActive {
                        NSLog("[PasteManager] ⚠️ Target app not active after first paste, retrying activation + Cmd+V")
                        self.activateTargetApp(targetApp)
                        DispatchQueue.main.asyncAfter(deadline: .now() + 0.10) {
                            self.simulatePaste()
                        }
                    }
                }

                // Restore previous clipboard content after paste has been processed.
                // Only restore when keepOnClipboard is false — otherwise the user wants
                // the transcription to stay on the clipboard.
                if let savedItems = savedItems, !savedItems.isEmpty {
                    DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                        self.restorePasteboard(pasteboard, from: savedItems)
                        NSLog("[PasteManager] Clipboard restored (all types)")
                    }
                }
            }
        }
    }

    // MARK: - App Activation

    private func activateTargetApp(_ targetApp: NSRunningApplication?) {
        let frontmost = NSWorkspace.shared.frontmostApplication
        let appToActivate = targetApp ?? frontmost
        guard let app = appToActivate else {
            NSLog("[PasteManager] ⚠️ No target app found")
            return
        }

        let isSelf = app.processIdentifier == ProcessInfo.processInfo.processIdentifier
        if isSelf {
            NSLog("[PasteManager] Target is YapYap itself, looking for previous app")
            if let fallback = frontmost,
               fallback.processIdentifier != ProcessInfo.processInfo.processIdentifier {
                NSLog("[PasteManager] Activating fallback app: \(fallback.localizedName ?? "unknown") (pid: \(fallback.processIdentifier))")
                Self.activateApp(fallback)
            } else {
                NSLog("[PasteManager] ⚠️ No suitable target app found — frontmost is YapYap")
            }
        } else {
            NSLog("[PasteManager] Activating app: \(app.localizedName ?? "unknown") (pid: \(app.processIdentifier))")
            Self.activateApp(app)
        }
    }

    /// Activate using cooperative API on macOS 14+, legacy API otherwise.
    private static func activateApp(_ app: NSRunningApplication) {
        if #available(macOS 14.0, *) {
            NSApplication.shared.yieldActivation(to: app)
            app.activate(from: NSRunningApplication.current, options: [])
        } else {
            app.activate()
        }
    }

    // MARK: - Pasteboard Save/Restore

    /// Save all items and their types from the pasteboard so we can do a full restore later.
    /// Returns nil if the pasteboard exceeds `maxPasteboardSaveBytes` (e.g. large image).
    private func savePasteboard(_ pasteboard: NSPasteboard) -> [[(NSPasteboard.PasteboardType, Data)]]? {
        var saved: [[(NSPasteboard.PasteboardType, Data)]] = []
        var totalBytes = 0
        for item in pasteboard.pasteboardItems ?? [] {
            var pairs: [(NSPasteboard.PasteboardType, Data)] = []
            for type in item.types {
                if let data = item.data(forType: type) {
                    totalBytes += data.count
                    if totalBytes > Self.maxPasteboardSaveBytes {
                        NSLog("[PasteManager] Pasteboard too large to save (%d bytes), skipping restore", totalBytes)
                        return nil
                    }
                    pairs.append((type, data))
                }
            }
            if !pairs.isEmpty {
                saved.append(pairs)
            }
        }
        return saved
    }

    /// Restore pasteboard to its previous state with all types preserved.
    private func restorePasteboard(_ pasteboard: NSPasteboard, from saved: [[(NSPasteboard.PasteboardType, Data)]]) {
        pasteboard.clearContents()
        var items: [NSPasteboardItem] = []
        for pairs in saved {
            let item = NSPasteboardItem()
            for (type, data) in pairs {
                item.setData(data, forType: type)
            }
            items.append(item)
        }
        if !items.isEmpty {
            pasteboard.writeObjects(items)
        }
    }

    // MARK: - CGEvent Helpers

    private func simulatePaste() {
        // Try creating event source; fall back to nil if it fails
        var source = CGEventSource(stateID: .hidSystemState)
        if source == nil {
            NSLog("[PasteManager] ⚠️ Named CGEventSource failed, trying with combinedSessionState")
            source = CGEventSource(stateID: .combinedSessionState)
        }
        if source == nil {
            NSLog("[PasteManager] ⚠️ All CGEventSource creation failed — attempting paste with nil source")
        }

        // Key code for 'V' is 0x09
        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: UInt16(kVK_ANSI_V), keyDown: true) else {
            NSLog("[PasteManager] ❌ Failed to create CGEvent keyDown")
            return
        }
        // Set only Cmd — overwrites any inherited modifier flags (e.g. Option from hotkey)
        keyDown.flags = .maskCommand
        keyDown.post(tap: .cghidEventTap)

        // 50ms delay between keyDown and keyUp — Electron apps (Slack, VS Code, Discord)
        // need time between events to register the paste. Posted from a background queue
        // to avoid blocking the main thread.
        DispatchQueue.global(qos: .userInteractive).asyncAfter(deadline: .now() + 0.05) {
            let keyUp = CGEvent(keyboardEventSource: source, virtualKey: UInt16(kVK_ANSI_V), keyDown: false)
            keyUp?.flags = .maskCommand
            keyUp?.post(tap: .cghidEventTap)
            NSLog("[PasteManager] Cmd+V posted (keyDown + 50ms + keyUp)")
        }
    }
}
